Repository team-mohaeng/mohaeng-server-release, pull requests merged in 2021-09, with the labels that each got.

#10 Feature/course/#9
  .gitignore
  src/api/course.ts
  src/class/Challenge.ts
  src/class/Course.ts
  src/dto/Course/Library/CourseLibraryResponseDTO.ts
  src/formatter/mohaengDateFormatter.ts
  src/index.ts
  src/service/courseService.ts
Labels: khyunjiee

#12 [DB] 필드 추가
  src/models/CompleteChallenge.ts
  src/models/User.ts
Labels: feat, kiyeon

#14 [회원가입] 파이어베이스로 이메일 회원가입 구현 #13
  .gitignore
  package-lock.json
  package.json
  src/api/auth.ts
  src/api/profile.ts
  src/config/index.ts
  src/dto/Auth/SignUp/request/SignUpRequestDTO.ts
  src/dto/Auth/SignUp/response/SignUpResponseDTO.ts
  src/errors.ts
  src/index.ts
  src/service/authService.ts
  src/service/profileService.ts
Labels: feat, kiyeon

#18 update: responseDTO 에서 date 관련 속성들 삭제
  src/dto/Course/Library/CourseLibraryResponseDTO.ts
  src/service/courseService.ts
Labels: khyunjiee

#19 [코스] 완료한 코스 조회 API
  src/api/course.ts
  src/dto/Course/Complete/CompleteCourseResponseDTO.ts
  src/service/courseService.ts
Labels: khyunjiee

#22 [회원가입] 회원가입 수정
  package.json
  src/dto/Auth/SignUp/response/SignUpResponseDTO.ts
  src/errors.ts
  src/models/User.ts
  src/service/authService.ts
Labels: bug, kiyeon

#16 [로그인] 이메일 로그인
  src/api/auth.ts
  src/dto/Auth/SignIn/request/SignInRequestDTO.ts
  src/dto/Auth/SignIn/response/SignInResponseDTO.ts
  src/errors.ts
  src/middleware/auth.ts
  src/middleware/dummyInterface.ts
  src/middleware/verifyFCM.ts
  src/service/authService.ts
Labels: feat, kiyeon

#23 [프로필] 닉네임 변경 코드 수정 및 API 완성 #17
  src/api/profile.ts
  src/middleware/auth.ts
  src/service/authService.ts
  src/service/profileService.ts
Labels: bug, feat, kiyeon

#26 [코스] 완료 코스, 코스 목록 조회 API 수정
  src/api/course.ts
  src/dto/Course/Complete/CompleteCourseResponseDTO.ts
  src/service/courseService.ts
Labels: khyunjiee

#27 [코스] 코스 진행하기
  src/api/course.ts
  src/dto/Course/Start/StartCourseResponseDTO.ts
  src/errors.ts
  src/service/courseService.ts
Labels: khyunjiee

#28 [회원가입/로그인] 코드 변경
  package-lock.json
  package.json
  src/api/auth.ts
  src/dto/Auth/SignUp/request/SignUpRequestDTO.ts
  src/index.ts
  src/middleware/verifyToken.ts
  src/models/User.ts
  src/service/authService.ts
Labels: bug, feat, kiyeon

#31 [코스] 코스 진행하기 API에 뱃지 로직 추가
  src/class/Badge.ts
  src/class/Level.ts
  src/service/courseService.ts
Labels: khyunjiee

#34 [회원가입] 회원가입 시 버그 수정
  src/models/User.ts
Labels: bug, kiyeon

#38 [이모지] 이모지 추가 API
  src/api/feed.ts
  src/dto/Feed/Emoji/request/AddEmojiRequestDTO.ts
  src/dto/Feed/Emoji/response/AddEmojiResponseDTO.ts
  src/errors.ts
  src/models/Emoji.ts
  src/service/feedService.ts
Labels: feat, kiyeon

#42 [리팩토링] 이름 수정 및 폴더 구조 변경
  src/api/feed.ts
  src/api/profile.ts
  src/dto/Feed/Create/request/CreateFeedRequestDTO.ts
  src/dto/Feed/Create/response/CreateFeedResponseDTO.ts
  src/dto/Feed/Delete/DeleteFeedResponseDTO.ts
  src/dto/Feed/response/feedCreateResponseDTO.ts
  src/service/feedService.ts
  src/service/profileService.ts
Labels: kiyeon, fix

#45 [피드] 안부 작성 수정
  src/models/Feed.ts
  src/service/feedService.ts
Labels: feat, kiyeon, fix

#46 [챌린지] 오늘의 챌린지 조회 API
  src/api/challenge.ts
  src/dto/Challenge/Today/TodayChallengeResponseDTO.ts
  src/errors.ts
  src/index.ts
  src/service/challengeService.ts
Labels: khyunjiee

#48 [코스] 코스 라이브러리 조회 API 수정
  src/models/index.ts
  src/service/courseService.ts
Labels: khyunjiee

#53 [피드] 커뮤니티 API
  src/api/feed.ts
  src/dto/Feed/Community/CommunityResponseDTO.ts
  src/dto/Feed/MyFeed/request/MyFeedRequestDTO.ts
  src/dto/Feed/MyFeed/response/MyFeedResponseDTO.ts
  src/dto/Feed/Read/request/ReadFeedRequestDTO.ts
  src/service/feedService.ts
Labels: feat, kiyeon

#54 [이모지] 이모지 API 수정
  src/service/feedService.ts
Labels: feat, kiyeon, fix

#56 [DB] is_written 필드 삭제
  src/models/User.ts
  src/service/feedService.ts
Labels: kiyeon, fix

#58 [피드] 피드 삭제 버그 수정
  src/api/feed.ts
  src/service/feedService.ts
Labels: feat, kiyeon, fix

#60 [피드] 피드 패널티 수정
  src/service/feedService.ts
Labels: feat, kiyeon, fix

#62 [피드] 내서랍장 수정
  src/service/feedService.ts
Labels: feat, kiyeon, fix

#65 [챌린지] 챌린지 인증하기 API
  src/api/challenge.ts
  src/dto/Challenge/Certification/CertificationChallengeResponseDTO.ts
  src/errors.ts
  src/models/CompleteChallenge.ts
  src/service/challengeService.ts
Labels: khyunjiee

#66 [코스] 코스 진행하기 버그
  src/service/courseService.ts
Labels: khyunjiee

#69 [코스] 완료 코스 조회 id 중복 이슈 해결
  src/service/courseService.ts
Labels: khyunjiee

#71 [코스] 코스 진행하기 버그 해결
  src/dto/Course/Start/StartCourseResponseDTO.ts
  src/service/courseService.ts
Labels: khyunjiee

#78 [DB] Skin, Character 테이블에 필드 추가
  src/models/Character.ts
  src/models/Skin.ts
Labels: khyunjiee

#73 [챌린지] 오늘의 챌린지 조회 버그 수정
  src/service/challengeService.ts
Labels: khyunjiee

#75 [챌린지] 챌린지 진행하기 버그 수정
  src/dto/Challenge/Certification/CertificationChallengeResponseDTO.ts
  src/service/challengeService.ts
Labels: khyunjiee

#80 [피드] 피드 버그 수정
  src/dto/Feed/Create/response/CreateFeedResponseDTO.ts
  src/service/feedService.ts
Labels: bug, kiyeon, fix

#82 [피드] 이모지 버그 수정
  src/dto/Feed/Community/CommunityResponseDTO.ts
  src/dto/Feed/MyFeed/response/MyFeedResponseDTO.ts
  src/service/feedService.ts
Labels: bug, kiyeon, fix

#83 [apidoc] apidoc 문서 작성
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  src/api/docs/feed.ts
  src/api/docs/profile.ts
  src/errors.ts
  src/service/feedService.ts
Labels: documentation, kiyeon

#85 [캐릭터] 캐릭터 선택 API
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  src/api/character.ts
  src/api/docs/character.ts
  src/dto/Character/request/SetCharacterRequestDTO.ts
  src/dto/Character/response/SetCharacterResponseDTO.ts
  src/errors.ts
  src/index.ts
  src/service/characterService.ts
Labels: feat, kiyeon

#87 [피드] 피드 신고 API
  src/api/feed.ts
  src/dto/Feed/Report/ReportFeedResponseDTO.ts
  src/errors.ts
  src/migrations/createTable/Report.ts
  src/models/Report.ts
  src/service/feedService.ts
Labels: feat, kiyeon

#92 [피드] 안부 버그 수정
  src/errors.ts
  src/models/User.ts
  src/service/feedService.ts
Labels: bug, kiyeon

#89 [피드] 안부 신고 apidoc 작성
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  src/api/docs/character.ts
  src/api/docs/feed.ts
  src/api/docs/profile.ts
Labels: documentation, kiyeon

#94 [프로필] 달성한 뱃지 조회 API
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  src/api/badge.ts
  src/api/docs/badge.ts
  src/api/profile.ts
  src/dto/Badge/getBadgeResponseDTO.ts
  src/index.ts
  src/service/badgeService.ts
  src/service/profileService.ts
Labels: feat, kiyeon
