Repository team-mohaeng/mohaeng-server-release, pull requests merged in 2021-10, with the labels that each got.

#95 [초기화] 코스/챌린지 초기화
  package.json
  src/controller/courseInit.ts
  src/index.ts
Labels: khyunjiee

#97 [프로필] 마이페이지 조회 API
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  src/api/docs/profile.ts
  src/api/profile.ts
  src/dto/Profile/MyPage/MyPageResponseDTO.ts
  src/service/profileService.ts
Labels: feat, kiyeon

#98 [소셜로그인] 카카오 로그인
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  package.json
  src/api/auth.ts
  src/api/docs/auth.ts
  src/config/index.ts
  src/dto/Auth/Kakao/request/KakaoRequestDTO.ts
  src/dto/Auth/Kakao/response/KakaoResponseDTO.ts
  src/models/User.ts
  src/service/authService.ts
Labels: feat, kiyeon

#107 [Home] 홈 조회 API
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  src/api/docs/home.ts
  src/api/home.ts
  src/dto/Home/HomeResponseDTO.ts
  src/index.ts
  src/service/challengeService.ts
  src/service/homeService.ts
Labels: feat

#111 [클래스] 클래스 수정
  src/class/Character.ts
  src/class/CharacterCard.ts
  src/class/Level.ts
  src/class/Skin.ts
Labels: bug, kiyeon, fix

#119 [소셜로그인] 소셜로그인
  apidoc/api_data.js
  apidoc/api_data.json
  package-lock.json
  package.json
  src/api/auth.ts
  src/api/docs/auth.ts
  src/dto/Auth/Kakao/request/KakaoRequestDTO.ts
  src/dto/Auth/Kakao/response/KakaoResponseDTO.ts
  src/dto/Auth/Social/request/SocialLogInRequestDTO.ts
  src/dto/Auth/Social/response/SocialLogInResponseDTO.ts
  src/errors.ts
  src/middleware/verifyToken.ts
  src/service/authService.ts
Labels: feat, kiyeon

#128 [비밀번호찾기] http method 변경
  src/api/auth.ts
Labels: bug, kiyeon, fix

#136 [채팅] 채팅 조회 (푸시 알림 조회) API
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  src/api/docs/home.ts
  src/api/docs/message.ts
  src/api/message.ts
  src/dto/Message/MessageResponseDTO.ts
  src/index.ts
  src/service/messageService.ts
Labels: khyunjiee

#141 [피드] 피드 작성 업데이트
  src/service/feedService.ts
Labels: feat, kiyeon

#143 [회원가입] 파이어베이스 수정
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  src/api/docs/auth.ts
  src/models/User.ts
  src/service/authService.ts
Labels: bug, kiyeon, fix

#149 [카카오 로그인] 카카오 로그인 토큰 유효성 검사
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  src/api/auth.ts
  src/api/docs/auth.ts
  src/middleware/kakao.ts
  src/service/authService.ts
Labels: bug, kiyeon, fix

#158 [캐릭터] 스킨 ios/aos 구분해주기
  apidoc/api_project.js
  apidoc/api_project.json
  src/api/character.ts
  src/api/docs/character.ts
  src/errors.ts
  src/service/characterService.ts
  src/service/feedService.ts
Labels: bug, kiyeon, fix

#162 Fix/course/#161
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  src/api/docs/course.ts
  src/dto/Course/Complete/CompleteCourseResponseDTO.ts
  src/service/courseService.ts
Labels: khyunjiee

#171 [챌린지] 챌린지 인증 시 연속 챌린지 체크 로직 수정
  src/service/challengeService.ts
Labels: khyunjiee

#174 [피드] 피드 작성 버그 수정
  src/service/feedService.ts
Labels: bug, kiyeon, fix

#176 [홈] 로직 수정
  src/service/homeService.ts
Labels: bug, khyunjiee

#204 [소셜로그인] 애플로그인 유효성 검사
  src/middleware/apple.ts
Labels: bug, kiyeon, fix

#206 [코스&챌린지] 더미 정렬 오류 수정
  src/service/challengeService.ts
  src/service/courseService.ts
Labels: khyunjiee

#208 [피드] 내서랍장 버그 수정
  src/service/feedService.ts
Labels: bug, kiyeon, fix

#210 [초기화] 코스 초기화 로직 삭제
  src/controller/courseInit.ts
  src/index.ts
Labels: khyunjiee
