Repository team-mohaeng/mohaeng-server-release, pull requests merged in 2021-11, with the labels that each got.

#214 [푸시알림] 이모지 붙였을 시 푸시알림
  package.json
  src/service/feedService.ts
Labels: khyunjiee

#213 [뱃지] 뱃지뷰 리스폰스 변경
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  src/api/docs/badge.ts
  src/service/badgeService.ts
Labels: bug, kiyeon, fix

#216 [피드] 커뮤니티 버그 수정
  src/errors.ts
  src/service/feedService.ts
Labels: bug, kiyeon, fix

#218 Fix/course/#217
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  src/api/docs/course.ts
  src/dto/Course/Complete/CompleteCourseResponseDTO.ts
  src/service/courseService.ts
Labels: khyunjiee, fix

#220 [회원가입] 이메일 중복 API
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  src/api/auth.ts
  src/api/docs/auth.ts
  src/dto/Auth/Email/EmailResponseDTO.ts
  src/service/authService.ts
Labels: feat, kiyeon

#222 [챌린지] 챌린지 인증하기 스킨 이미지 버그
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  src/api/challenge.ts
  src/api/docs/challenge.ts
  src/service/challengeService.ts
  src/service/homeService.ts
Labels: khyunjiee, fix

#227 [푸시알림] TIMEZONE 버그
  package.json
  src/service/messageService.ts
Labels: khyunjiee, fix

#230 [피드] 피드 작성 버그 수정
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  src/api/docs/feed.ts
  src/api/feed.ts
  src/service/feedService.ts
Labels: bug, kiyeon, fix

#228 [피드] 안부 작성 가능 여부 버그 수정
  src/formatter/mohaengDateFormatter.ts
  src/service/feedService.ts
Labels: bug, kiyeon, fix

#232 [홈] 버그 수정
  src/service/challengeService.ts
  src/service/courseService.ts
Labels: khyunjiee, fix

#234 [피드] 피드 작성 가능 여부 수정
  src/formatter/mohaengDateFormatter.ts
  src/service/feedService.ts
Labels: bug, kiyeon, fix

#236 [피드] 피드 작성 가능 여부 버그 수정
  src/service/feedService.ts
Labels: bug, kiyeon, fix

#238 [피드] 레벨업시 캐릭터 카드 주는 로직 수정
  src/service/feedService.ts
Labels: bug, kiyeon, fix

#244 [피드] 신고한 사용자의 안부 보이지 않게 하기
  src/controller/dummyController.ts
  src/controller/password.ts
  src/controller/sendReport.ts
  src/migrations/createTable/Block.ts
  src/models/Block.ts
  src/models/User.ts
  src/service/feedService.ts
Labels: feat, kiyeon

#240 [피드] 신고 10회 누적 시 회원 탈퇴
  src/models/User.ts
  src/service/feedService.ts
Labels: feat, kiyeon

#245 [피드] 신고한 사용자의 안부 보이지 않게 하기
  src/service/feedService.ts
Labels: bug, kiyeon

#247 [챌린지] 캐릭터타입 코드 수정
  src/service/challengeService.ts
Labels: bug, kiyeon

#249 [블락] 블락 API
  src/api/auth.ts
  src/api/docs/auth.ts
  src/dto/Auth/Block/BlockResponseDTO.ts
  src/errors.ts
  src/service/authService.ts
  src/service/feedService.ts
Labels: feat, kiyeon

#251 [APIDOC] 블락 기능 APIDOC
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  src/api/docs/auth.ts
Labels: documentation, kiyeon

#253 [피드] 커뮤니티 페이징
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  src/api/docs/feed.ts
  src/api/feed.ts
  src/service/feedService.ts
Labels: feat, kiyeon

#255 [피드] 커뮤니티 안부 개수 수정
  src/service/feedService.ts
Labels: bug, kiyeon, fix
